### ISSUE TITLE
Sorry, I cannot find hs in python

### ISSUE THREAD

**Issue by LucasDurian** [tbarnetlamb/hyphen#12]
Hello mate, I am not sure where can I find the "hs", I managed to use "pip install hs" and so on, unfortunately, I failled. Could you please tell me how to install it. thx!

**Comment by tbarnetlamb** [comment]
Hyphen is not (yet?) available in pip. One has to build it from source. Instructions for doing so are at:

https://github.com/tbarnetlamb/hyphen/blob/master/BUILDING.md

The short version is that you should clone the git repo and execute the script `hyphen/build-extn.py`.

You may also wish to look at the automated test scripts for travis and appveyor as they handle building hyphen in the various standard test environments that I use.

**Comment by tbarnetlamb** [comment]
PS: please let me know if any of that is not clear!

**Comment by tbarnetlamb** [comment]
Seems that the issue was resolved.
