### ISSUE TITLE
Full functionality testing for installation scripts? 

### ISSUE THREAD

**Issue by InfamousPlatypus** [tbarnetlamb/hyphen#21]
I'm trying to get scripts to install automatically, what all would I need to check to see that it worked properly, could I just tell python to add two numbers together, but in Haskell and if it works, everything is good, or is there some other "section" that I need to check?
Thanks!

**Comment by tbarnetlamb** [comment]
That's probably a reasonable first test but it wouldn't guarantee that everything is working.

One test you could try is:
```
python3 hyphen_examples_full.py
``` 

This will run ~all the tests from the documentation and a few other tests, in each of the GIL and interrupt modes.

For even more extensive testing possibilities, you can look at the tests run in CI. [see here](https://github.com/tbarnetlamb/hyphen/blob/main/.github/workflows/ci.yml). This does things like simulate interrupts to verify that all the various modes are working the way they are meant to.

For a slightly less intensive test, you could modify `hyphen_examples_full` so it didn't run all the GIL/interrupt modes.

**Comment by InfamousPlatypus** [comment]
That sounds great! Thanks!
