### ISSUE TITLE
Ran into a build issue on Ubuntu LTS 18.04 and fixed by adding #include <signal.h>

### ISSUE THREAD

**Issue by sjwhitmore** [tbarnetlamb/hyphen#7]
I got this error output when running the build script.
ubuntu@ip-172-31-35-17:~/hyphen$ python3 hyphen/build-extn.py
/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c: In function ‘c_installHaskellCtrlCHandler’:

/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c:435:19: error:
     error: ‘SIGINT’ undeclared (first use in this function); did you mean ‘T_UINT’?
       if (PyOS_getsig(SIGINT) == python_siginthandler     && haskell_siginthandler)
                       ^~~~~~
                       T_UINT

/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c:435:19: error:
     note: each undeclared identifier is reported only once for each function it appears in
/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c: In function ‘c_reinstallPythonCtrlCHandler’:

/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c:447:19: error:
     error: ‘SIGINT’ undeclared (first use in this function); did you mean ‘T_UINT’?
       if (PyOS_getsig(SIGINT) == &compound_sigint_handler && python_siginthandler)
                       ^~~~~~
                       T_UINT
/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c: In function ‘PyInit_hslowlevel’:

/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c:1401:39: error:
     error: ‘SIGINT’ undeclared (first use in this function); did you mean ‘T_UINT’?
       python_siginthandler  = PyOS_getsig(SIGINT);
                                           ^~~~~~
                                           T_UINT
/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c: In function ‘pyhs_free’:

/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c:1445:50: error:
     error: ‘SIGINT’ undeclared (first use in this function); did you mean ‘T_UINT’?
       PyOS_sighandler_t sigint_handler = PyOS_getsig(SIGINT);
                                                      ^~~~~~
                                                      T_UINT
`gcc' failed in phase `C Compiler'. (Exit code: 1)
Traceback (most recent call last):
  File "hyphen/build-extn.py", line 130, in <module>
    subprocess.check_call(invocation + ['-no-link'])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ghc', '-dynamic', '-shared', '-fPIC', '-no-hs-main', '-fwarn-unused-imports', '-cpp', '/home/ubuntu/hyphen/hyphen/lowlevel_src/Hyphen.hs', '/home/ubuntu/hyphen/hyphen/lowlevel_src/hyphen_c.c', '-i/home/ubuntu/hyphen/hyphen/lowlevel_src', '-hidir', '/home/ubuntu/hyphen/hyphen/lowlevel_inter', '-odir', '/home/ubuntu/hyphen/hyphen/lowlevel_inter', '-I/usr/include/python3.6m', '-package', 'ghc', '-lHSrts_thr-ghc8.0.2\n', '-lpython3.6m', '-no-link']' returned non-zero exit status 1.

I fixed it by adding #include <signal.h> to line 4 on hyphen/lowlevel_src/hyphen_c.c.  I've forked & pushed updated branch to my fork at https://github.com/sjwhitmore/hyphen/tree/include-signal-h if you'd like to see the code.  Thanks!

**Comment by tbarnetlamb** [comment]
Thanks for this! I'm looking at the change, I'm pretty amazed that this worked on other platforms without that include :)

I have created a PR to merge your changes, and I will just wait for the CI results to get back so I can be sure that I don't need to change the patch to avoid creating problems (e.g. on other platforms).

Please let me know if you hit any other issues as you're using hyphen.

**Comment by sjwhitmore** [comment]
Thank you! Appreciated :)

I’m trying to use hyphen to call two functions in this library —
https://github.com/uber/queryparser — I’m a newcomer to Haskell so kind of
troubleshooting my way through. I followed your posted instructions for
linking other Haskell code (moved the queryparser repo inside hyphen) and
tried to link it using the find_and_load_haskell_source() command, but got
this error -- if you have any pointers on how to fix it or compile the
library in a more appropriate way I'd very much appreciate it! Otherwise
will keep finding my own way :) thanks, Sam
ubuntu@ip-172-31-35-17:~/hyphen$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyphen
>>> hyphen.find_and_load_haskell_source()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/hyphen/hyphen/source_loading.py", line 136, in
find_and_load_haskell_source
    fetch_source_modules(found_modules)
  File "/home/ubuntu/hyphen/hyphen/caches.py", line 51, in
fetch_source_modules
    module_cache.update(hslowlevel.import_src(*paths))
hyphen.HsException: <interactive>: fatal:
    cannot find object file ‘/home/ubuntu/hyphen/queryparser/Setup.dyn_o’
    while linking an interpreted expression

**Comment by tbarnetlamb** [comment]
Hmm. The find_and_load_haskell_source functionality is designed for loading a few short Haskell modules (each a single file) into python scope. It's not really going to be a great fit for loading the code from whole packages, especially packages that you didn't write yourself. Moreover, the queryparser repo actually contains 5 different packages, so there are 5 different directories that are the 'root directory for haskell modules', and to use find_and_load_haskell_source you'd need to basically consolidate those 5 directory trees into a single tree (which would also have to have your python source at the root). It's... possible... I guess, but I wouldn't recommend it.

I would recommend, instead, building each of the 5 component packages using one of the two standard haskell build tools, and then having that tool make them available to hyphen.

There are two main haskell build tools: stack and cabal. Cabal is older (and was the only one that existed at the time hyphen was written); stack is more modern and emphasizes sandboxing and reproducible builds. I would recommend stack for most purposes nowadays. I did

```
TBL:hyphen tbl$ git clone https://github.com/uber/queryparser.git
Cloning into 'queryparser'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 741 (delta 0), reused 6 (delta 0), pack-reused 727
Receiving objects: 100% (741/741), 373.31 KiB | 831.00 KiB/s, done.
Resolving deltas: 100% (342/342), done.
TBL:hyphen tbl$ emacs stack.yaml # I'll replace the existing stack.yaml file, which is just there for running tests on windows, with a new one that requests that we build not only the dependencies for hyphen, but also the queryparser packages (and their dependencies)...
TBL:hyphen tbl$ cat stack.yaml 

resolver: lts-10.4
packages:
- .
- 'queryparser'
- 'queryparser/dialects/vertica'
- 'queryparser/dialects/hive'
- 'queryparser/dialects/presto'


extra-deps: [ 'test-framework-quickcheck-0.3.0'
            , 'file-location-0.4.9.1'
            , 'fixed-list-0.1.6'
            ]

# arch: i386
arch: x86_64
TBL:hyphen tbl$ stack build
<snip>
TBL:hyphen tbl$ stack exec -- python3 hyphen/build-extn.py
<snip>
Linking /Users/tbl/Documents/current/written/projects/current-home-projects/research etc/hyphen/hyphen/hslowlevel.cpython-37m-darwin.so ...
TBL:hyphen tbl$ stack exec -- python3 
Python 3.7.5 (default, Oct 28 2019, 07:13:20) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyphen
>>> hyphen.importing.EXPECTED_EMPTY += ['Database', 'Database.Sql', 'Database.Sql.Util', 'Database.Sql.Vertica' ]
>>> import hs.Database.Sql.Vertica, hs.Database.Sql.Util.Scope
>>> ^D

```

and that seemed to work, at least as far as importing the modules. Notes

- Note that I have to append to hyphen.importing.EXPECTED_EMPTY. This is necessary because of an annoying impedence mismatch between Haskell packages and Python packages. There's a comment explaining the situation in hyphen.importing. You'll probably need to add more (e.g. 'Database.Sql.Presto').

- Note that when stack installs packages, it installs them to a segregated location so that it does not interfere with other stuff in the system. This means that I have to do 'stack exec --- python' above so hyphen can see queryparser. Under the hood, I think 'stack exec' just works by setting environment variables:

```
TBL:hyphen tbl$ diff <(env | sort) <(stack exec -- env | sort)
2a3,6
> GHC_PACKAGE_PATH=/Users/tbl/Documents/current/written/projects/current-home-projects/research etc/hyphen/.stack-work/install/x86_64-osx/lts-10.4/8.2.2/pkgdb:/Users/tbl/.stack/snapshots/x86_64-osx/lts-10.4/8.2.2/pkgdb:/Users/tbl/.stack/programs/x86_64-osx/ghc-8.2.2/lib/ghc-8.2.2/package.conf.d
> HASKELL_DIST_DIR=.stack-work/dist/x86_64-osx/Cabal-2.0.1.0
> HASKELL_PACKAGE_SANDBOX=/Users/tbl/.stack/snapshots/x86_64-osx/lts-10.4/8.2.2/pkgdb
> HASKELL_PACKAGE_SANDBOXES=/Users/tbl/Documents/current/written/projects/current-home-projects/research etc/hyphen/.stack-work/install/x86_64-osx/lts-10.4/8.2.2/pkgdb:/Users/tbl/.stack/snapshots/x86_64-osx/lts-10.4/8.2.2/pkgdb:
8c12
< PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
---
> PATH=/Users/tbl/FULL_PATH_CENSORED/x86_64-osx/lts-10.4/8.2.2/bin:/Users/tbl/.stack/snapshots/x86_64-osx/lts-10.4/8.2.2/bin:/Users/tbl/.stack/compiler-tools/x86_64-osx/ghc-8.2.2/bin:/Users/tbl/.stack/programs/x86_64-osx/ghc-8.2.2/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
13a18
> STACK_EXE=/Library/Haskell/ghc-8.4.3-x86_64/bin/stack
22c27,28
< _=/usr/bin/env
---
> _=/usr/local/bin/stack
> __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0

```
so if you want to avoid ugly "stack exec --- " prefixes to your python3 invocations, you can probably set the same env variables using os.env within python.

Please let me know if this works for you.

PS: maybe better to transfer this discussion to email? Up to you. If you prefer so, just let me know and I'll use your publicly-available address to continue the conversation.

**Comment by tbarnetlamb** [comment]
PS: sorry that the above email is a little terse. I hope it didn't come across as unfriendly! I was writing in haste while traveling...

**Comment by sjwhitmore** [comment]
No problem! I really appreciate the help and will move to email for future
correspondence :) will let you know how it goes in a separate thread once I
try out this method. Thank you!

**Comment by sjwhitmore** [comment]
Hi,

I couldn't find your email on Github so just following up on this thread
(Feel free to respond directly to my email!).

Thank you for your detailed instructions! I got hyphen to build with the
queryparser libraries by following your guidelines.  I now have two issues,
one which you may be able to answer quickly and one I think which is just a
problem with one of the queryparser Haskell modules (which you may have
intuition on solving, so including it just in case, but no worries if too
hard to unravel).

Problem #1 (simpler): How do I cast an argument as Haskell type
Data.Text.Lazy?
The function "parse" in the module "Database.Sql.Vertica.Parser" expects
input type Data.Text.Lazy -- it looks like a Python string is not
automatically converted to this type.
parse :: Text -> Either P.ParseError (VerticaStatement RawNames Range)

ubuntu@ip-172-31-35-17:~/hyphen$ stack exec -- python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyphen
>>> hyphen.importing.EXPECTED_EMPTY += ['Database', 'Database.Sql',
'Database.Sql.Util', 'Database.Sql.Vertica', 'Demo' ]
>>> import hs.Database.Sql.Vertica.Parser
>>> hs.Database.Sql.Vertica.Parser.parse("SELECT * from foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/hyphen/hyphen/marshall_ctor.py", line 230, in
apply_marshalled
    return hyphen.marshall_obj_to_py.hs_to_py(applyFromPyArgs(*full_args))
  File "/home/ubuntu/hyphen/hyphen/marshall_ctor.py", line 214, in
applyFromPyArgs
    marshall_obj_to_hs.py_to_hs(args[i], arg_types_[i]) for i in
range(len(args))])
TypeError: Expected Haskell object for parameter 2, not None

Problem #2 (more complex problem, most likely with one of the queryparser
modules themselves): I also included the Demo module in the stack.yaml for
hyphen, as it has some simple functions I'd like to use.  However, I got
the following error when trying to import this module in Python. If you
have any intuition as to which of the functions in
https://github.com/uber/queryparser/blob/master/demo/src/Demo.hs could be
causing this error, that would be incredibly helpful -- I'm somewhat at a
loss as to which are at fault.
ubuntu@ip-172-31-35-17:~/hyphen$ stack exec -- python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyphen
>>> hyphen.importing.EXPECTED_EMPTY += ['Database', 'Database.Sql',
'Database.Sql.Util', 'Database.Sql.Vertica', 'Demo' ]
>>> import hs.Demo
Traceback (most recent call last):
  File "/home/ubuntu/hyphen/hyphen/importing.py", line 228, in load_module
    marshall_module(data_ns, type_ns, module_to_write)
  File "/home/ubuntu/hyphen/hyphen/importing.py", line 172, in
marshall_module
    (k, _process_data_ns_item(k, v))  for (k, v) in data_namespace.items())
  File "/home/ubuntu/hyphen/hyphen/importing.py", line 172, in <genexpr>
    (k, _process_data_ns_item(k, v))  for (k, v) in data_namespace.items())
  File "/home/ubuntu/hyphen/hyphen/importing.py", line 139, in
_process_data_ns_item
    return hyphen.marshall_obj_to_py.hs_to_py(item)
  File "/home/ubuntu/hyphen/hyphen/marshall_obj_to_py.py", line 141, in
hs_to_py
    return tyc_class.interpret(obj)
  File "/home/ubuntu/hyphen/hyphen/marshall_ctor.py", line 371, in interpret
    hs_null, hslowlevel.apply(co_dacon, obj))):
TypeError: Ambiguous application: You tried to apply an object of type
t a -> GHC.Types.Bool
to objects of type
[[(Database.Sql.Type.Names.QSchemaName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Names.QSchemaName
Data.Functor.Identity.Identity a_0), Database.Sql.Type.Names.QTableName
GHC.Base.Maybe a_0 -> Control.Monad.Trans.Except.ExceptT
(Database.Sql.Type.Scope.ResolutionError a_0)
(Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RTableName a_0),
Database.Sql.Type.Names.DatabaseName () ->
Database.Sql.Type.TableProps.Existence, Database.Sql.Type.Names.QSchemaName
Database.Sql.Type.Names.No () -> Database.Sql.Type.TableProps.Existence,
Database.Sql.Type.Names.QTableName Database.Sql.Type.Names.No () ->
Database.Sql.Type.TableProps.Existence,
[(Database.Sql.Type.Names.TableAlias a_0,
[Database.Sql.Type.Names.RColumnRef a_0])] ->
Database.Sql.Type.Names.QTableName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.WithColumns
Database.Sql.Type.Scope.RTableRef a_0), Database.Sql.Type.Names.QSchemaName
GHC.Base.Maybe a_0 -> Control.Monad.Trans.Except.ExceptT
(Database.Sql.Type.Scope.ResolutionError a_0)
(Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RCreateSchemaName
a_0), Database.Sql.Type.Names.QTableName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RCreateTableName
a_0), [(GHC.Base.Maybe (Database.Sql.Type.Scope.RTableRef a_0),
[Database.Sql.Type.Names.RColumnRef a_0])] ->
Database.Sql.Type.Names.QColumnName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Names.RColumnRef a_0),
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.DatabaseName ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QSchemaName
Database.Sql.Type.Names.No ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QTableName Database.Sql.Type.Names.No ())
Database.Sql.Type.Scope.SchemaMember)) -> (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.DatabaseName ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QTableName
Database.Sql.Type.Names.No ()) Database.Sql.Type.Scope.SchemaMember)),
a_0)) -> (Database.Sql.Type.Scope.Catalog, a_0), Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.DatabaseName ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QTableName
Database.Sql.Type.Names.No ()) Database.Sql.Type.Scope.SchemaMember)),
[Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ()] ->
Database.Sql.Type.Scope.Catalog, Database.Sql.Type.Names.DatabaseName () ->
Database.Sql.Type.Scope.Catalog)]].
After resolving type variables, this amounts to applying an object of type
[(Database.Sql.Type.Names.QSchemaName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Names.QSchemaName
Data.Functor.Identity.Identity a_0), Database.Sql.Type.Names.QTableName
GHC.Base.Maybe a_0 -> Control.Monad.Trans.Except.ExceptT
(Database.Sql.Type.Scope.ResolutionError a_0)
(Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RTableName a_0),
Database.Sql.Type.Names.DatabaseName () ->
Database.Sql.Type.TableProps.Existence, Database.Sql.Type.Names.QSchemaName
Database.Sql.Type.Names.No () -> Database.Sql.Type.TableProps.Existence,
Database.Sql.Type.Names.QTableName Database.Sql.Type.Names.No () ->
Database.Sql.Type.TableProps.Existence,
[(Database.Sql.Type.Names.TableAlias a_0,
[Database.Sql.Type.Names.RColumnRef a_0])] ->
Database.Sql.Type.Names.QTableName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.WithColumns
Database.Sql.Type.Scope.RTableRef a_0), Database.Sql.Type.Names.QSchemaName
GHC.Base.Maybe a_0 -> Control.Monad.Trans.Except.ExceptT
(Database.Sql.Type.Scope.ResolutionError a_0)
(Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RCreateSchemaName
a_0), Database.Sql.Type.Names.QTableName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RCreateTableName
a_0), [(GHC.Base.Maybe (Database.Sql.Type.Scope.RTableRef a_0),
[Database.Sql.Type.Names.RColumnRef a_0])] ->
Database.Sql.Type.Names.QColumnName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Names.RColumnRef a_0),
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.DatabaseName ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QSchemaName
Database.Sql.Type.Names.No ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QTableName Database.Sql.Type.Names.No ())
Database.Sql.Type.Scope.SchemaMember)) -> (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.DatabaseName ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QTableName
Database.Sql.Type.Names.No ()) Database.Sql.Type.Scope.SchemaMember)),
a_0)) -> (Database.Sql.Type.Scope.Catalog, a_0), Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.DatabaseName ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QTableName
Database.Sql.Type.Names.No ()) Database.Sql.Type.Scope.SchemaMember)),
[Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ()] ->
Database.Sql.Type.Scope.Catalog, Database.Sql.Type.Names.DatabaseName () ->
Database.Sql.Type.Scope.Catalog)] -> GHC.Types.Bool
 to objects of type
[[(Database.Sql.Type.Names.QSchemaName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Names.QSchemaName
Data.Functor.Identity.Identity a_0), Database.Sql.Type.Names.QTableName
GHC.Base.Maybe a_0 -> Control.Monad.Trans.Except.ExceptT
(Database.Sql.Type.Scope.ResolutionError a_0)
(Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RTableName a_0),
Database.Sql.Type.Names.DatabaseName () ->
Database.Sql.Type.TableProps.Existence, Database.Sql.Type.Names.QSchemaName
Database.Sql.Type.Names.No () -> Database.Sql.Type.TableProps.Existence,
Database.Sql.Type.Names.QTableName Database.Sql.Type.Names.No () ->
Database.Sql.Type.TableProps.Existence,
[(Database.Sql.Type.Names.TableAlias a_0,
[Database.Sql.Type.Names.RColumnRef a_0])] ->
Database.Sql.Type.Names.QTableName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.WithColumns
Database.Sql.Type.Scope.RTableRef a_0), Database.Sql.Type.Names.QSchemaName
GHC.Base.Maybe a_0 -> Control.Monad.Trans.Except.ExceptT
(Database.Sql.Type.Scope.ResolutionError a_0)
(Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RCreateSchemaName
a_0), Database.Sql.Type.Names.QTableName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Scope.RCreateTableName
a_0), [(GHC.Base.Maybe (Database.Sql.Type.Scope.RTableRef a_0),
[Database.Sql.Type.Names.RColumnRef a_0])] ->
Database.Sql.Type.Names.QColumnName GHC.Base.Maybe a_0 ->
Control.Monad.Trans.Except.ExceptT (Database.Sql.Type.Scope.ResolutionError
a_0) (Control.Monad.Trans.Writer.Lazy.WriterT [Data.Either.Either
(Database.Sql.Type.Scope.ResolutionError a_0)
(Database.Sql.Type.Scope.ResolutionSuccess a_0)]
Data.Functor.Identity.Identity) (Database.Sql.Type.Names.RColumnRef a_0),
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.DatabaseName ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QSchemaName
Database.Sql.Type.Names.No ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QTableName Database.Sql.Type.Names.No ())
Database.Sql.Type.Scope.SchemaMember)) -> (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.DatabaseName ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QTableName
Database.Sql.Type.Names.No ()) Database.Sql.Type.Scope.SchemaMember)),
a_0)) -> (Database.Sql.Type.Scope.Catalog, a_0), Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.DatabaseName ()) (Data.HashMap.Base.HashMap
(Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ())
(Data.HashMap.Base.HashMap (Database.Sql.Type.Names.QTableName
Database.Sql.Type.Names.No ()) Database.Sql.Type.Scope.SchemaMember)),
[Database.Sql.Type.Names.QSchemaName Database.Sql.Type.Names.No ()] ->
Database.Sql.Type.Scope.Catalog, Database.Sql.Type.Names.DatabaseName () ->
Database.Sql.Type.Scope.Catalog)]].
The variables ["a_0"] are present in the input but not the result and
cannot be resolved.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/hyphen/hyphen/importing.py", line 233, in load_module
    "Failed to import haskell module '{}'".format(module_name)) from e
ImportError: Failed to import haskell module 'hs.Demo'

Thank you very much again for your help!
